# Generated by Django 5.1.6 on 2025-04-07 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_type', models.CharField(max_length=255, unique=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('max_per_day', models.PositiveIntegerField(default=60)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('imga', models.ImageField(blank=True, null=True, upload_to='tour_images')),
                ('imgb', models.ImageField(blank=True, null=True, upload_to='tour_images')),
                ('weekday_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weekend_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uemail', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('num_visitors', models.PositiveIntegerField()),
                ('booking_date', models.DateField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parktour.tour')),
            ],
        ),
    ]
