# Generated by Django 5.1.6 on 2025-04-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parktour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='uemail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
