# Generated by Django 5.1.6 on 2025-06-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parktour', '0002_alter_booking_uemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booked_at_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
