# Generated by Django 5.1.6 on 2025-06-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parktour', '0003_booking_booked_at_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='uemail',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
