# Generated by Django 5.1.6 on 2026-02-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parktour', '0004_alter_booking_uemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_done_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('PAY_ON_ARRIVAL', 'Pay on arrival'), ('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PAY_ON_ARRIVAL', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='stripe_session_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
