# Generated by Django 5.1.6 on 2026-02-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parktour', '0006_alter_booking_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('PAY_ON_ARRIVAL', 'Pay on arrival'), ('PAID', 'Paid')], default='PAY_ON_ARRIVAL', max_length=25),
        ),
    ]
