# Generated by Django 5.1.6 on 2026-02-02 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parktour', '0007_alter_booking_payment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='payment_status',
            new_name='payment_method',
        ),
    ]
