# Generated by Django 5.1.6 on 2026-02-02 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parktour', '0008_rename_payment_status_booking_payment_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='payment_method',
            new_name='payment_status',
        ),
    ]
