# Generated by Django 5.1.6 on 2026-02-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parktour', '0009_rename_payment_method_booking_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_stage',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed')], default='CONFIRMED', max_length=25),
        ),
    ]
