# Generated by Django 5.1.6 on 2025-06-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='priority_code',
            field=models.IntegerField(default=50),
        ),
    ]
