# Generated by Django 5.1.6 on 2025-06-28 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppticket', '0002_supportticket_priority_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportticket',
            name='staff',
        ),
    ]
