# Generated by Django 5.1.6 on 2025-03-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0002_alter_category_options_alter_cartitem_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
