# Generated by Django 5.1.6 on 2025-04-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0004_alter_order_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cart_max',
            field=models.PositiveIntegerField(default=8),
        ),
    ]
