# Generated by Django 5.1.6 on 2025-06-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0005_product_cart_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='uemail',
            field=models.EmailField(max_length=20, null=True),
        ),
    ]
