# Generated by Django 5.1.6 on 2026-02-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0006_order_uemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_done_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('CASH_ON_DELIVERY', 'Cash on delivery'), ('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='CASH_ON_DELIVERY', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_session_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
