# Generated by Django 5.1.6 on 2026-02-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0008_alter_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('CASH_ON_DELIVERY', 'Cash on delivery'), ('PAID', 'Paid')], default='CASH_ON_DELIVERY', max_length=25),
        ),
    ]
