# Generated by Django 5.1.6 on 2026-02-02 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0009_alter_order_payment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_status',
            new_name='payment_method',
        ),
    ]
