# Generated by Django 5.1.6 on 2025-04-03 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communityforum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumpost',
            name='video_link',
        ),
    ]
