# Generated by Django 5.1.6 on 2025-04-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityforum', '0002_remove_forumpost_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
